server:
  port: 8099
spring:
  application:
    name: springboot-hbase
#hbase:
#  config: {"hbase.zookeeper.quorum":"192.168.61.150","hbase.zookeeper.property.clientPort":"2181"}
hbase:
  config:
    hbase.zookeeper.quorum: localhost
    hbase.zookeeper.port: 2181
#    hbase.zookeeper.znode: /hbase
#    hbase.client.keyvalue.maxsize: 1572864000



